### ISSUE TITLE
Copy element to buffer does not work

### ISSUE THREAD

**Issue by romanmyko** [ita-social-projects/Forum#674]
![Image](https://github.com/ita-social-projects/Forum/assets/123646984/4ec589d7-15b6-4f34-b25d-aec2922b1b13)

**Comment by Lvyshnevska** [comment]
There is no bug in the the functionality of copying to clipboard. 
The Clipboard: writeText() method is available only in secure contexts (HTTPS). 
Since the site is using HTTP (not secure), the functionality of copying to clipboard is not available. 

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
